// <auto-generated />
using MicroelectronicsWarehouse.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MicroelectronicsWarehouse.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250526095029_FirstCreate")]
    partial class FirstCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MicroelectronicsWarehouse.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Passive Components"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Active Components"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Electromechanical Components"
                        });
                });

            modelBuilder.Entity("MicroelectronicsWarehouse.Entities.Component", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SupplierId");

                    b.ToTable("Components");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Standard 10k ohm resistor used in various circuits.",
                            Name = "Resistor 10kΩ",
                            Quantity = 100,
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Electrolytic capacitor with 100 microfarads capacity.",
                            Name = "Capacitor 100uF",
                            Quantity = 50,
                            SupplierId = 2
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Description = "General purpose NPN transistor for signal amplification.",
                            Name = "NPN Transistor BC547",
                            Quantity = 200,
                            SupplierId = 3
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 3,
                            Description = "Electromechanical relay operating at 5 volts.",
                            Name = "Relay 5V",
                            Quantity = 75,
                            SupplierId = 1
                        });
                });

            modelBuilder.Entity("MicroelectronicsWarehouse.Entities.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContactEmail = "info@ElectroParts.com",
                            Name = "ElectroParts Ltd."
                        },
                        new
                        {
                            Id = 2,
                            ContactEmail = "contact@chipmaker.com",
                            Name = "MicroSupply"
                        },
                        new
                        {
                            Id = 3,
                            ContactEmail = "info@nanoparts.com",
                            Name = "NanoChip Co."
                        });
                });

            modelBuilder.Entity("MicroelectronicsWarehouse.Entities.Component", b =>
                {
                    b.HasOne("MicroelectronicsWarehouse.Entities.Category", "Category")
                        .WithMany("Components")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MicroelectronicsWarehouse.Entities.Supplier", "Supplier")
                        .WithMany("Components")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("MicroelectronicsWarehouse.Entities.Category", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("MicroelectronicsWarehouse.Entities.Supplier", b =>
                {
                    b.Navigation("Components");
                });
#pragma warning restore 612, 618
        }
    }
}
